USE hr;
DELIMITER $$
CREATE FUNCTION exibir_quantidade_pessoas_contratadas_por_mes_e_ano(MES INT, ANO INT)
RETURNS INT READS SQL DATA
BEGIN
    DECLARE FUNC_CONTRATADOS INT;
    SELECT COUNT(*) FROM hr.employees WHERE MONTH(HIRE_DATE) = MES AND YEAR(HIRE_DATE) = ANO INTO FUNC_CONTRATADOS;
    RETURN FUNC_CONTRATADOS;
END $$
