SELECT CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME) 'Nome completo', 
J.JOB_TITLE Cargo, JH.START_DATE 'Data de início do cargo', D.DEPARTMENT_NAME Departamento
FROM hr.employees E
INNER JOIN hr.job_history JH on JH.EMPLOYEE_ID = E.EMPLOYEE_ID
INNER JOIN hr.jobs J on J.JOB_ID = JH.JOB_ID
INNER JOIN hr.departments D on D.DEPARTMENT_ID = JH.DEPARTMENT_ID
ORDER BY CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME) DESC, Cargo;
