SELECT CONCAT_WS(' ', FIRST_NAME, LAST_NAME) AS 'Nome completo', 
START_DATE AS 'Data de início', SALARY AS 'Salário' from employees e
INNER JOIN job_history jh ON e.EMPLOYEE_ID = jh.EMPLOYEE_ID
INNER JOIN jobs j ON j.JOB_ID = jh.JOB_ID
WHERE MONTH(START_DATE)= 01 OR MONTH(START_DATE)=02 OR MONTH(START_DATE)=03  
GROUP BY CONCAT_WS(' ', FIRST_NAME, LAST_NAME), START_DATE, Salário 
ORDER BY CONCAT_WS(' ', FIRST_NAME, LAST_NAME), START_DATE;
